[pytest]
# Test path folder
testpaths = tests

# File name patern
python_files = test_*.py *_test.py

# Class name paterns
python_classes = Test*

# Function name pattern
python_functions = test_*

# Default log level
log_cli = true
log_cli_level = INFO
log_format = %(asctime)s [%(levelname)s] %(message)s
log_date_format = %H:%M:%S

# Custom marker definition (test categories)
markers =
    unit: Unit testler
    api: API integration tests
    e2e: End-to-end UI tests
    smoke: Kritik path tests
    regression: Full regression suite
    slow: 5 saniyeden uzun süren testler

# asyncio mode - async testler için
asyncio_mode = auto
